//
let resultCode:any = {
	RESULT_OK            : 0,
	RESULT_XK            : 1,
	RESULT_SYSTEM        : 50,
	
	RESULT_ITEM_TIPS     : 400,
	RESULT_PET_TIPS      : 600,
	RESULT_ACTIVITY_TIPS : 1000,
	RESULT_TASK_TIPS     : 1500,
	RESULT_ROLE_TIPS     : 2000,
}

resultCode.RESULT_RANK_IN_THREE               = resultCode.RESULT_SYSTEM + 1 //恭喜%s在%s排行中成为全服第%s名.
resultCode.RESULT_RANK_FIRST                  = resultCode.RESULT_SYSTEM + 2 //%s超群绝伦，以非凡的实力在%s排行中超越了%s，成为全服第一.
resultCode.RESULT_LITTLE_THREE                = resultCode.RESULT_SYSTEM + 3 //恭喜%s在%s排行中成功超越了%s成为第%s名.
//resultCode.RESULT_SKYTOWER_FLOOR              = resultCode.RESULT_SYSTEM + 4 //%s玩家勇闯天空之塔，成为全服首个通过%d层的勇者。
resultCode.RESULT_WROLDBOSS_KILLER            = resultCode.RESULT_SYSTEM + 5 //%s玩家在终极魔龙活动中对魔龙造成最后致命一击！
//resultCode.RESULT_CALL_GOLDEN_HERO            = resultCode.RESULT_SYSTEM + 6 //%s玩家祭坛召集中召集成功，获得女神%s%s。
//resultCode.RESULT_INVITE_GOLDEN_HERO          = resultCode.RESULT_SYSTEM + 7 //%s玩家在命运邀请中，意外邀请到金色部下%d。
resultCode.RESULT_CHAMPION_SERVER_FIRST       = resultCode.RESULT_SYSTEM + 8 //%s玩家成为全服首个通过%d的勇者，获得%d晶石奖励！
resultCode.RESULT_REFRESH_CHAMPION            = resultCode.RESULT_SYSTEM + 9  //竞技场可挑战次数已全部恢复。
//resultCode.RESULT_REFRESH_SKYTOWER            = resultCode.RESULT_SYSTEM + 10 //天空之塔已经重置为第1层。
//resultCode.RESULT_REFRESH_ITEMTRADE           = resultCode.RESULT_SYSTEM + 11 //市场物品的回收量和库存已经重置。
resultCode.RESULT_REFRESH_HERO                = resultCode.RESULT_SYSTEM + 12 //部下召集已重置为绿色法阵，免费转动和挑战次数恢复。
//resultCode.RESULT_ROBBER_MAX_PIECE            = resultCode.RESULT_SYSTEM + 13 //您拥有%d达到上限数量500，无法再获取
//resultCode.RESULT_WUDOU_MATCH                 = resultCode.RESULT_SYSTEM + 14 //斗技大赛-单人赛制已经火热开启，现在正在决出%s比赛，大家可以进行比赛观战。
//resultCode.RESULT_WUDOU_APPLY_NOTICE          = resultCode.RESULT_SYSTEM + 15 //距离斗技大赛-单人赛制参赛报名时间截止还有1个小时，请想参赛的玩家尽快报名。
//resultCode.RESULT_WUDOU_RANK                  = resultCode.RESULT_SYSTEM + 16 //本次斗技大赛获得冠军是%s，亚军是%s，季军是%s，祝贺他们！
//resultCode.RESULT_WUDOU_CANCEL                = resultCode.RESULT_SYSTEM + 17 //本次斗技大赛由于报名人数不足，暂不开启！
resultCode.RESULT_WORLDQUESTION_OPEN          = resultCode.RESULT_SYSTEM + 18 //贵族考试活动开启了，小伙伴们赶快前去一展才华！
//resultCode.RESULT_FACTIONMAP_KILLBOSS         = resultCode.RESULT_SYSTEM + 19 //经过大家的齐心协力，最后%s以迅雷不及掩耳之势给予BOSS致命一击，成功击杀BOSS！
//resultCode.RESULT_FACTIONMAP_LEAVE            = resultCode.RESULT_SYSTEM + 20 //全体军团成员获得通关奖励，副本内成员将在10秒后被送出副本。
//resultCode.RESULT_FACTIONMAP_CREATE           = resultCode.RESULT_SYSTEM + 21 //我已开启%d副本了！兄弟们，为了大家的利益冲啊！
resultCode.RESULT_WORLDQUESTION_PREVIEW       = resultCode.RESULT_SYSTEM + 22 //贵族考试将在10分钟后开启，请各位做好答题准备，答对有奖励哦。
//resultCode.RESULT_FACTIONMAP_FIRST            = resultCode.RESULT_SYSTEM + 23 //%s军团众志成城，齐心协力一举把%d副本通关！成为全服首次通过%d副本的军团！
resultCode.RESULT_WORLDQUESTION_LOTTERY       = resultCode.RESULT_SYSTEM + 24 //%s在贵族考试中答题正确，被幸运女神选中，获得答题惊喜%s
//resultCode.RESULT_WUDOU_APPLYEND              = resultCode.RESULT_SYSTEM + 25 //斗技大赛-单人赛制参赛报名已截止，晚上7点将开启比赛，开启前可押注冠军赢取晶石奖励。
//resultCode.RESULT_RIDDLE_BOX_OPEN             = resultCode.RESULT_SYSTEM + 26 //宝山矮人在%s挖矿时挖出了不少宝物，赶快前去拾取啊！
//resultCode.RESULT_SPACE_TIME_ROBBER_OPEN      = resultCode.RESULT_SYSTEM + 27 //一群时空盗贼偷偷的进入了%s打砸掳掠、大肆破坏。各位勇士请速速前往%s击杀盗贼，惩恶除奸！
//resultCode.RESULT_SPACE_TIME_ROBBER_CLEAR     = resultCode.RESULT_SYSTEM + 28 //由于各方勇士精诚协作、奋勇杀敌，作恶的盗贼们丢盔弃甲、溃不成军，如丧家之犬般遁走时空裂缝。
//resultCode.RESULT_ONLINE_QUESTION_CLOSE       = resultCode.RESULT_SYSTEM + 29 //抢答活动已经结束，下次活动开启请留意系统公告！
//resultCode.RESULT_ONLINE_QUESTION_START       = resultCode.RESULT_SYSTEM + 30 //智力抢答要开始了，1分钟内在系统频道选出答案的玩家，可以获得礼物一份。
//resultCode.RESULT_FIRST_RECHARGE              = resultCode.RESULT_SYSTEM + 31 //%s通过首次充值获得神将【斯特拉】，女皇大陆上从此又多了一名强者！
resultCode.RESULT_CREATE_FACTION              = resultCode.RESULT_SYSTEM + 32 //%s成功创建了%s军团，欢迎各界勇士加入！
//resultCode.RESULT_ROBBER_KILL_BOSS            = resultCode.RESULT_SYSTEM + 33 //%s玩家在混沌世界%d地%d区成功击杀了堕落魔人，获得%d！
//resultCode.RESULT_QIANGDA_RANK                = resultCode.RESULT_SYSTEM + 34 //在线答题前3名抢答成功的玩家为%s、%s、%s，获得%s！
//resultCode.RESULT_WORLDBOSS_RANK              = resultCode.RESULT_SYSTEM + 35 //终极魔龙活动伤害排名前3的玩家分别是：第一名%s、第二名%s、第三名%s，恭喜他们！
//resultCode.RESULT_ROBBER_BOSS_KILLED          = resultCode.RESULT_SYSTEM + 36 //堕落魔人已死亡，%d存入您所在军团仓库！
//resultCode.RESULT_ROBBER_MUTIL_OPEN           = resultCode.RESULT_SYSTEM + 37 //混沌世界受到不明空间力量的冲击，在30分钟内怪物掉落率为平时的2倍！
//resultCode.RESULT_ROBBER_MUTIL_CLOSE          = resultCode.RESULT_SYSTEM + 38 //随着时间的流逝，混沌世界受到冲击而产出的变化现在恢复了正常！
//resultCode.RESULT_CAMPAGIN_MUTIL_OPEN         = resultCode.RESULT_SYSTEM + 39 //世界受到战斗之神的眷顾，在60分钟内所有关卡的经验值为平时的2倍！
//resultCode.RESULT_CAMPAGIN_MUTIL_CLOSE        = resultCode.RESULT_SYSTEM + 40 //随着时间的流逝，关卡中的收益恢复了正常！
//resultCode.RESULT_LOTTERY_PET                 = resultCode.RESULT_SYSTEM + 41 //%s玩家通过五一幸运轮盘获得了神将【%s】
//resultCode.RESULT_MYSTICAL_STONE              = resultCode.RESULT_SYSTEM + 42 //%s玩家通过五一充值大礼获得了神将【%s】
resultCode.RESULT_FACTION_CHANGE_LEADER       = resultCode.RESULT_SYSTEM + 43 //团长%s由于3天不上线，现由%s继承成为新团长
//resultCode.RESULT_MAGIC_STONE_INCREASE_BEGIN  = resultCode.RESULT_SYSTEM + 44 //女王大陆受到幸运女神的眷顾，所有冒险者魔导石的升级概率得到提升！
//resultCode.RESULT_MAGIC_STONE_INCREASE_END    = resultCode.RESULT_SYSTEM + 45 //幸运女神离去，魔导石的升级概率恢复正常！
//resultCode.RESULT_SACRIFICE_INCREASE_BEGIN    = resultCode.RESULT_SYSTEM + 46 //女王大陆受到幸运女神的眷顾，所有冒险者法阵祭祀的升级概率得到提升！
//resultCode.RESULT_SACRIFICE_INCREASE_END      = resultCode.RESULT_SYSTEM + 47 //幸运女神离去，法阵祭祀的升级概率恢复正常！
//resultCode.RESULT_LOSTTEMPLE_REFRESH          = resultCode.RESULT_SYSTEM + 48 //天赐一个神像，赶快去寻找并拾取它吧！
//resultCode.RESULT_LOSTTEMPLE_PICKCOUNT        = resultCode.RESULT_SYSTEM + 49 //神像捡取次数已达上限，请攻击其他玩家获得神像！
//resultCode.RESULT_LOSTTEMPLE_MAXCOUNT         = resultCode.RESULT_SYSTEM + 50 //您已获得神像最大奖励，给其他小伙伴留点奖励吧！
//resultCode.RESULT_NOT_ACTIVE_TIME             = resultCode.RESULT_SYSTEM + 51 //不在活动时间
//resultCode.RESULT_ZHENYING_END                = resultCode.RESULT_SYSTEM + 52 //【%d兵】在%s，%s，%s的英勇带领下打败了【%d兵】获得了伟大的胜利
//resultCode.RESULT_ZHENYING_BEGIN              = resultCode.RESULT_SYSTEM + 53 //阵营争夺战即将开始，请各位少爷踊跃参与为阵营出一份力，收获更大奖励。
//resultCode.RESULT_CALL_GOLDEN_HERO_MONTHCARD  = resultCode.RESULT_SYSTEM + 54 //%s玩家祭坛召集中召集成功，获得女神%s%s。【通过月卡赠送的120抽】
//resultCode.RESULT_RECHARGE_GET_PET            = resultCode.RESULT_SYSTEM + 55 //%s恭喜%s通过充值获得了典藏女神%s！
//resultCode.RESULT_RECHARGE_GET_ITEM           = resultCode.RESULT_SYSTEM + 56 //%s通过充值获得了%s * 2，可进化为史诗品质！

//resultCode.RESULT_MONSTER_SIEGE_OPEN          = resultCode.RESULT_SYSTEM + 60 //魔物攻城开始了！深渊魔王和他的将领正对我们发起了进攻！英勇的美斗士请前往战场抗敌，成为守护英雄！
//resultCode.RESULT_MONSTER_SIEGE_FAIL          = resultCode.RESULT_SYSTEM + 61 //由于无法抵御深渊魔王的猛烈攻势，全体美斗士无法获得击退奖励！请各位好好提升实力，争取下次成功击退深渊魔王！
//resultCode.RESULT_MONSTER_SIEGE_SUCCESS       = resultCode.RESULT_SYSTEM + 62 //通过大家的努力，成功将深渊魔王和他的将领击退了！参与战斗的玩家将会获得击退奖励！
//resultCode.RESULT_MONSTER_SIEGE_RANK          = resultCode.RESULT_SYSTEM + 63 //角色%s、角色%s、角色%s、角色%s和角色%s在这次抵御深渊魔王的进攻中表现突出，成为这次的守护英雄获得英雄奖励！
//resultCode.RESULT_FACTION_LEAVE_UNION         = resultCode.RESULT_SYSTEM + 64 //%s军团离开了联盟！
//resultCode.RESULT_FACTION_ADD_UNION           = resultCode.RESULT_SYSTEM + 65 //%s军团加入了联盟！

//resultCode.RESULT_WUDOUTEAM_MATCH             = resultCode.RESULT_SYSTEM + 66 //斗技大赛-组队赛制已经火热开启，现在正在决出%s比赛，大家可以进行比赛观战。
//resultCode.RESULT_WUDOUTEAM_APPLY_NOTICE      = resultCode.RESULT_SYSTEM + 67 //距离斗技大赛-组队赛制参赛报名时间截止还有1个小时，请想参赛的玩家尽快报名。
//resultCode.RESULT_WUDOUTEAM_RANK              = resultCode.RESULT_SYSTEM + 68 //本次斗技大赛-组队赛制获得冠军是%s，亚军是%s，季军是%s，祝贺他们！
//resultCode.RESULT_WUDOUTEAM_CANCEL            = resultCode.RESULT_SYSTEM + 69 //本次斗技大赛-组队赛制由于报名人数不足，暂不开启！
//resultCode.RESULT_WUDOUTEAM_APPLYEND          = resultCode.RESULT_SYSTEM + 70 //斗技大赛-组队赛制参赛报名已截止，晚上8点将开启比赛，开启前可押注冠军赢取晶石奖励。

//resultCode.RESULT_FACTIONWARSERVER_PRESTART   = resultCode.RESULT_SYSTEM + 71 //跨服军团战将在一个小时候开始，请相关的军团成员准时参加比赛！
//resultCode.RESULT_FACTIONWARSERVER_START      = resultCode.RESULT_SYSTEM + 72 //跨服军团赛已经火热开启，请获得资格的军团成员迅速进入活动，为军团抢夺令牌展现军团实力！
//resultCode.RESULT_FACTIONWARSERVER_END        = resultCode.RESULT_SYSTEM + 73 //本届跨服军团战4强已诞生，一起祝贺他们。
//resultCode.RESULT_FACTIONWARSERVER_FINALEND   = resultCode.RESULT_SYSTEM + 74 //本届跨服军团战冠军已诞生，一起祝贺他们。

//resultCode.RESULT_RUNMAN_PRESTART             = resultCode.RESULT_SYSTEM + 75 //迷惑宫殿还有十分钟就开始了，请玩家进入宫殿内准备冲刺。
//resultCode.RESULT_RUNMAN_NOTSTART             = resultCode.RESULT_SYSTEM + 76 //当前活动还未开启，请做好准备耐心等待。
//resultCode.RESULT_RUNMAN_START                = resultCode.RESULT_SYSTEM + 77 //宫殿活动正式开始，各位少爷请用最快的速度到达最高层。
//resultCode.RESULT_RUNMAN_RIGHTDOOR            = resultCode.RESULT_SYSTEM + 78 //恭喜你，少爷选择了正确的门。
//resultCode.RESULT_RUNMAN_WRONGDOOR            = resultCode.RESULT_SYSTEM + 79 //很遗憾，少爷选择了错误的门。
//resultCode.RESULT_RUNMAN_DROP5                = resultCode.RESULT_SYSTEM + 80 //%s脚一滑倒退了5关迷宫，让我们在世界频道为他加油吧！
//resultCode.RESULT_RUNMAN_FIRST                = resultCode.RESULT_SYSTEM + 81 //恭喜%s以最快的速度达到宫殿的%d关。
//resultCode.RESULT_RUNMAN_RISE10               = resultCode.RESULT_SYSTEM + 82 //%s有一股一步登殿的气势，马不停蹄前进了10关迷宫，恭喜他！
//resultCode.RESULT_RUNMAN_CLOSE                = resultCode.RESULT_SYSTEM + 83 //活动即将结束，请少爷抓紧时间通关
//
//resultCode.RESULT_USE_ITEM                    = resultCode.RESULT_SYSTEM + 84 //无敌幸运星%s 在打开 %s 的时候, 获得了%s！
//resultCode.RESULT_RUNMAN_END                  = resultCode.RESULT_SYSTEM + 85 //奇异梦境活动圆满结束
//resultCode.RESULT_DEAD_FIELD_BEGIN            = resultCode.RESULT_SYSTEM + 86 //死亡领域活动正式开启！谁才是真正的王者，赶快来试炼吧！
//resultCode.RESULT_DEAD_FIELD_END              = resultCode.RESULT_SYSTEM + 87 //死亡领域活动已结束，期待下次更多勇者参与。
//resultCode.RESULT_DEAD_FIELD                  = resultCode.RESULT_SYSTEM + 88 //%s玩家勇闯死亡领域，成为全服首个通过%d层的勇者。
//resultCode.RESULT_PET_ADVANCEEX               = resultCode.RESULT_SYSTEM + 89 //恭喜%s通过【异界邀请】成功邀请特殊部下%s
//resultCode.RESULT_SECRET_LAND_PREPARE         = resultCode.RESULT_SYSTEM + 90 //密语境地即将开始！5分钟后密语境地将会开放福利，考验各位少爷的时刻即将到来。
//resultCode.RESULT_SECRET_LAND_OPEN            = resultCode.RESULT_SYSTEM + 91 //密语境地开始了！英勇的少爷请带上实力和知识挑战自己，获得丰富奖励吧！
//resultCode.RESULT_SECRET_LAND_CLOSE           = resultCode.RESULT_SYSTEM + 92 //密语境地活动到此结束，参加本次活动的少爷们可以获得活动奖励。
//resultCode.RESULT_HALLOWEEN_GET_PET           = resultCode.RESULT_SYSTEM + 93 //恭喜%s玩家通过使用%s得了【%s】
//resultCode.RESULT_KITE_CREATE                 = resultCode.RESULT_SYSTEM + 94 //春分节活动的风筝在%s刷新，请各位玩家前去拾取。
//resultCode.RESULT_EASTER_EGG_CREATE           = resultCode.RESULT_SYSTEM + 95 //复活节彩蛋在%s刷新，请各位玩家前去拾取。
//resultCode.SERVER_CHAT_GROUP_COUNT_LIMIT      = resultCode.RESULT_SYSTEM + 96 //聊天组已经达到全服上限
//resultCode.RESULT_MEMBERS_COUNT_LIMIT         = resultCode.RESULT_SYSTEM + 97 //讨论组成员达到上限
//resultCode.RESULT_UNIONPVP_FIRST_START        = resultCode.RESULT_SYSTEM + 98 //联盟赛初赛开始
//resultCode.RESULT_UNIONPVP_FIRST_END          = resultCode.RESULT_SYSTEM + 99 //联盟赛初赛结束,决赛开始准备
//resultCode.RESULT_UNIONPVP_SECOND_START       = resultCode.RESULT_SYSTEM + 100 //联盟赛决赛开始
//resultCode.RESULT_UNIONPVP_SECOND_END         = resultCode.RESULT_SYSTEM + 101 //联盟赛决赛结束
//resultCode.RESULT_UNIONPVP_SECOND_SUCCESS     = resultCode.RESULT_SYSTEM + 102 //%s军团赢得了比赛
//resultCode.RESULT_UNIONPVP_APPLY_END          = resultCode.RESULT_SYSTEM + 103 //本届联盟赛名单已经确定
//resultCode.RESULT_UNIONPVP_NO_NODE            = resultCode.RESULT_SYSTEM + 104 //不在参赛列表中
//resultCode.RESULT_UNIONPVP_NO_ROOM            = resultCode.RESULT_SYSTEM + 105 //没有这个副本
//resultCode.RESULT_UNIONPVP_NO_PLR_DATA        = resultCode.RESULT_SYSTEM + 106 //没有玩家数据
//resultCode.RESULT_UNIONPVP_NO_ENTER           = resultCode.RESULT_SYSTEM + 107 //这个阶段不能进入副本
//resultCode.RESULT_UNIONPVP_FACTION_TIME       = resultCode.RESULT_SYSTEM + 108 //加入军团时间不足%s天
//resultCode.RESULT_UNIONPVP_FACTION_TIME     = resultCode.RESULT_SYSTEM + 109 //加入军团时间不足%s天
//resultCode.RESULT_UNIONPVP_HAS_FLAG           = resultCode.RESULT_SYSTEM + 110 //已经有旗帜了
//resultCode.RESULT_UNIONPVP_TIME_FLAG          = resultCode.RESULT_SYSTEM + 111 //时间还未到,不能获取积分
//resultCode.RESULT_UNIONPVP_DIFFERENT          = resultCode.RESULT_SYSTEM + 112 //在不同地图,不能进行此操作
//resultCode.RESULT_UNIONPVP_DEAD_WAIT          = resultCode.RESULT_SYSTEM + 113 //对方或者你处于死亡等待状态
//resultCode.RESULT_UNIONPVP_NO_UNION           = resultCode.RESULT_SYSTEM + 114 //联盟信息错误
//resultCode.RESULT_UNIONPVP_CANNOT_PREPARE     = resultCode.RESULT_SYSTEM + 115 //当前不是准备阶段
//resultCode.RESULT_UNIONPVP_SET_READY          = resultCode.RESULT_SYSTEM + 116 //已经设置成功
//resultCode.RESULT_UNIONPVP_HAS_MEMBER         = resultCode.RESULT_SYSTEM + 117 //这个位置已经有人了
//resultCode.RESULT_UNIONPVP_NO_MEMBER          = resultCode.RESULT_SYSTEM + 118 //对方没有人参加战斗
//resultCode.RESULT_UNIONPVP_REFRESH_FLAG       = resultCode.RESULT_SYSTEM + 119 //第三个地图刷新了大旗帜
//resultCode.RESULT_UNIONPVP_MATCH_NOT_START    = resultCode.RESULT_SYSTEM + 120 //比赛名单还未确定，请耐心等待
//resultCode.RESULT_UNIONPVP_APPLY_ALREADY      = resultCode.RESULT_SYSTEM + 121 //已经在名单之中了,不能重复报名
//resultCode.RESULT_UNIONPVP_COUNT              = resultCode.RESULT_SYSTEM + 122 //这种状态不能叠加
//resultCode.RESULT_UNIONPVP_ENTER_TIME         = resultCode.RESULT_SYSTEM + 123 //退出再次进入需要等待60秒
//resultCode.RESULT_UNIONPVP_MY_SIDE            = resultCode.RESULT_SYSTEM + 124 //不能攻击己方单位
//resultCode.RESULT_UNIONPVP_BOSS_TIME          = resultCode.RESULT_SYSTEM + 125 //不能连续攻击
//resultCode.RESULT_UNIONPVP_REFRESH_BOX        = resultCode.RESULT_SYSTEM + 126 //刷新了宝箱，大家快去捡啊
//resultCode.RESULT_UNIONPVP_ADD_BUFF           = resultCode.RESULT_SYSTEM + 127 //你获得了一个%s
//resultCode.RESULT_UNIONPVP_LEVEL_LIMIT        = resultCode.RESULT_SYSTEM + 128 //联盟军团平均等级不足5级，无法报名
//resultCode.RESULT_UNIONPVP_LEADER_COMBAT      = resultCode.RESULT_SYSTEM + 129 //团长正在战斗，或者不在活动内
//resultCode.RESULT_UNIONPVP_BUFF_YIN_SHEN      = resultCode.RESULT_SYSTEM + 130 //对方处于隐身状态
//resultCode.RESULT_UNIONPVP_NO_FACTION         = resultCode.RESULT_SYSTEM + 131 //你没有军团
//resultCode.RESULT_UNIONPVP_NO_LEADER          = resultCode.RESULT_SYSTEM + 132 //你不是军团长
//resultCode.RESULT_UNIONPVP_NO_APPLY_STAGE     = resultCode.RESULT_SYSTEM + 133 //当前不是报名阶段
resultCode.RESULT_NOT_COMMON_COMBAT_TEAM      = resultCode.RESULT_SYSTEM + 134 //没有骑士团或者不在同一个骑士团
resultCode.RESULT_TEAM_PVE_LAYER_COUNT_LIMIT  = resultCode.RESULT_SYSTEM + 135 //今天进度已通关两次，请等待明天继续
resultCode.RESULT_TEAM_PVE_SUCCESS            = resultCode.RESULT_SYSTEM + 136 //你已经成功通关了
resultCode.RESULT_TEAM_PVE_RESETTING          = resultCode.RESULT_SYSTEM + 137 //记录正在重置中，凌晨之后开放
resultCode.RESULT_UNIONPVP_NOT_APPLY          = resultCode.RESULT_SYSTEM + 138 //你所在的联盟没有获得参赛资格
//resultCode.RESULT_RIDE_ADVANCEEX              = resultCode.RESULT_SYSTEM + 139 //%s通过【坐骑激活】成功激活%s
//resultCode.RIDE_ADVANCEEX_SUCCESS             = resultCode.RESULT_SYSTEM + 140 //您通过【坐骑激活】成功激活坐骑%s，以下是本次召集所用材料：%s
//resultCode.RIDE_ADVANCEEX_SUCCESS_FAILE       = resultCode.RESULT_SYSTEM + 141 //不好意思，您激活失败了，放入的素材消失了
//resultCode.RESULT_UNIONPVPS_GAME16            = resultCode.RESULT_SYSTEM + 142 //跨服联盟战8强战正火热进行中
//resultCode.RESULT_UNIONPVPS_GAME8             = resultCode.RESULT_SYSTEM + 143 //跨服联盟战4强战正火热进行中
//resultCode.RESULT_UNIONPVPS_GAME4             = resultCode.RESULT_SYSTEM + 144 //跨服联盟战半决赛正火热进行中
//resultCode.RESULT_UNIONPVPS_GAME2             = resultCode.RESULT_SYSTEM + 145 //跨服联盟战决赛战正火热进行中
//resultCode.RIDE_FEED_ADD_VALUE                = resultCode.RESULT_SYSTEM + 146 //喂养成功，坐骑成长度增加%d
//resultCode.RESULT_TASK_IS_TAKEN               = resultCode.RESULT_SYSTEM + 147 //任务已经被领取
//resultCode.RESULT_TASK_IS_OVERDUE             = resultCode.RESULT_SYSTEM + 148 //任务已经过期
//resultCode.RESULT_UNIONPVPS_USEITEM           = resultCode.RESULT_SYSTEM + 149 //成功使用道具
//resultCode.RESULT_UNIONPVPS_USEITEM_MAX       = resultCode.RESULT_SYSTEM + 150 //使用次数已满
//resultCode.RESULT_UNIONPVPS_USEITEM_CD        = resultCode.RESULT_SYSTEM + 151 //使用冷却中
//resultCode.RESULT_ALREADY_HAVE_PUB_TASK       = resultCode.RESULT_SYSTEM + 152 //已经领取到任务
//resultCode.RESULT_TASK_POOL_IS_FULL           = resultCode.RESULT_SYSTEM + 153 //任务池已满
//resultCode.RESULT_GUOZHANCST_MAX_ARMY         = resultCode.RESULT_SYSTEM + 154 //达到部队出征上限，无法再出征
//resultCode.RESULT_GUOZHANCST_ATTACK_ERROR1    = resultCode.RESULT_SYSTEM + 155 //需要攻破外城墙
//resultCode.RESULT_MARRY_NOT_FRIEND            = resultCode.RESULT_SYSTEM + 156 //结婚好友限制
//resultCode.RESULT_MARRY_FRINEDSHIP_LIMIT      = resultCode.RESULT_SYSTEM + 157 //结婚情缘值限制
//resultCode.RESULT_MARRY_IN_BLACKLIST          = resultCode.RESULT_SYSTEM + 158 //结婚黑名单限制
//resultCode.RESULT_MARRY_SPOUSE_LIMIT          = resultCode.RESULT_SYSTEM + 159 //结婚已婚限制
//resultCode.RESULT_MARRY_TEAM_ONLINE_MEMBER    = resultCode.RESULT_SYSTEM + 160 //结婚队伍有人离线
//resultCode.RESULT_MARRY_ITEM_LIMIT            = resultCode.RESULT_SYSTEM + 161 //结婚物品限制
//resultCode.RESULT_MARRY_DIVORCE_TIME_LIMIT    = resultCode.RESULT_SYSTEM + 162 //申请离婚时间限制
//resultCode.RESULT_MARRY_DIVORCE_ONLINE_LIMIT  = resultCode.RESULT_SYSTEM + 163 //申请离婚对方不在线
//resultCode.RESULT_MARRY_DIVORCE_REJECT        = resultCode.RESULT_SYSTEM + 164 //申请离婚被拒绝
//resultCode.RESULT_MARRY_DIVORCE_RMB_LIMIT     = resultCode.RESULT_SYSTEM + 165 //强制离婚钱不够
//resultCode.RESULT_MARRY_DIVORCE_LOST_TIME     = resultCode.RESULT_SYSTEM + 166 //失踪离婚时间不够
//resultCode.RESULT_MARRY_LEVEL_LIMIT           = resultCode.RESULT_SYSTEM + 167 //结婚等级限制
//resultCode.RESULT_GUOZHANCST_ATTACK_SUCCESS   = resultCode.RESULT_SYSTEM + 168 //攻击城墙成功，获得10点积分
//resultCode.RESULT_MARRY_WEDDING_TIME          = resultCode.RESULT_SYSTEM + 169 //有婚礼正在进行中
//resultCode.RESULT_MARRY_WEDDING               = resultCode.RESULT_SYSTEM + 170 //%s和%s喜结良缘，祝他们白头到老！
//resultCode.RESULT_GUOZHANCST_START            = resultCode.RESULT_SYSTEM + 171 //世界霸主争霸赛正在火热进行中！请有志之士进入异界纷争，为国家争夺霸主之位！
//resultCode.RESULT_GUOZHANCST_CLOSE            = resultCode.RESULT_SYSTEM + 172 //经过激烈的比拼，%d服名成为新一届世界霸主！他们将收到各个服务器的进贡奖励！
//resultCode.RESULT_GUOZHANCST_DEFECE           = resultCode.RESULT_SYSTEM + 173 //%d服成功守护住了皇城，他们将成为新一届的世界霸主！
//resultCode.RESULT_GUOZHANCST_ATTACK           = resultCode.RESULT_SYSTEM + 174 //通过各方精英合作无间，已经成功攻破皇城的防守！新的世界霸主即将诞生！
//resultCode.RESULT_GUOZHANCST_MARCH            = resultCode.RESULT_SYSTEM + 175 //部队成功出发
//resultCode.RESULT_GUOZHANCST_BOMB             = resultCode.RESULT_SYSTEM + 176 //进攻方发动一个攻城炸弹
//resultCode.RESULT_MARRY_REJECT                = resultCode.RESULT_SYSTEM + 177 //申请结婚被拒绝
//resultCode.RESULT_MARRY_REQUEST_WAIT          = resultCode.RESULT_SYSTEM + 178 //申请结婚等待
//resultCode.RESULT_MARRY_SAME_SEX              = resultCode.RESULT_SYSTEM + 179 //申请结婚双方必须是异性
//resultCode.RESULT_RIDE_AUTO_FEED_ITEM_EMPTY   = resultCode.RESULT_SYSTEM + 180 //自动喂养道具消耗完成
//resultCode.RESULT_RIDE_AUTO_FEED_SCHE_FULL    = resultCode.RESULT_SYSTEM + 181 //自动喂养进度已满
//resultCode.RESULT_RIDE_AUTO_FEED_ONGOING      = resultCode.RESULT_SYSTEM + 182 //当前有自动喂养正在进行中，请先取消
//resultCode.RESULT_MARRY_PICK_UP_LIMIT         = resultCode.RESULT_SYSTEM + 183 //捡糖果次数限制
//resultCode.RESULT_MARRY_LUXURY_WEDDING        = resultCode.RESULT_SYSTEM + 184 //%s和%s在巴恩斯城堡举行豪华婚礼，还有花车游街，每次停留会发喜糖给大家，大家快去拿喜糖吧！
//resultCode.RESULT_GUOZHANCST_ATTACK_ERROR2    = resultCode.RESULT_SYSTEM + 185 //准备阶段不能发起进攻
//resultCode.RESULT_MARRY_TEAM_THREE_PEOPLE     = resultCode.RESULT_SYSTEM + 186 //结婚时队伍中有三个人
//resultCode.RESULT_RIDE_AUTO_FEED_ITEM_LIMIT   = resultCode.RESULT_SYSTEM + 187 //自动喂养道具不足
//resultCode.RESULT_RED_FACTION_DAILY_LIMIT     = resultCode.RESULT_SYSTEM + 188 //已经达到军团每日发红包上限
//resultCode.RESULT_RED_PLR_DAILY_LIMIT         = resultCode.RESULT_SYSTEM + 189 //已经达到每日领取上限
//resultCode.RESULT_RED_ENVELOPE_OVER_TIME      = resultCode.RESULT_SYSTEM + 190 //红包已过期
//resultCode.RESULT_RED_ENVELOPE_ALREADY        = resultCode.RESULT_SYSTEM + 191 //你已经领取过该红包了
//resultCode.RESULT_RED_SEND_PLR_DAILY_LIMIT    = resultCode.RESULT_SYSTEM + 192 //每天只能发一个红包
//resultCode.RESULT_RED_CONTRIBUTE_LIMIT        = resultCode.RESULT_SYSTEM + 193 //你当前的活跃值不够

//resultCode.RESULT_FACTIONWAR_NOTICE_APPLY     = resultCode.RESULT_SYSTEM + 194 //距离军团赛-预选赛的参赛报名时间截止还有1个小时，请要参赛的军团尽快报名！团长、副团长或长老均可为军团报名。
//resultCode.RESULT_FACTIONWAR_APPLY_END        = resultCode.RESULT_SYSTEM + 195 //军团赛参赛报名已截止，晚上8点将开启比赛，请成功报名的军团成员准时参加比赛！
//resultCode.RESULT_FACTIONWAR_START1           = resultCode.RESULT_SYSTEM + 196 //公会战淘汰赛1/8赛已经火热开启，请获得资格的军团成员迅速进入活动，为军团抢夺令牌展现军团实力！
//resultCode.RESULT_FACTIONWAR_START2           = resultCode.RESULT_SYSTEM + 197 //公会战淘汰赛1/4赛已经火热开启，请获得资格的军团成员迅速进入活动，为军团抢夺令牌展现军团实力！
//resultCode.RESULT_FACTIONWAR_SENIOR           = resultCode.RESULT_SYSTEM + 198 //第一阶段比赛已经火热结束，请参赛双方公会前往第二阶段布置精英赛！
//resultCode.RESULT_FACTIONWAR_TWO              = resultCode.RESULT_SYSTEM + 199 //恭喜%s、%s、%s和%s以的强大实力获得了进入半决赛的资格！半决赛将在周日晚上7点开始！敬请各位关注！
//resultCode.RESULT_FACTIONWAR_THREE            = resultCode.RESULT_SYSTEM + 200 //恭喜%s、%s在半决赛中获得胜利，争夺冠军！%s、%s争夺季军
//resultCode.RESULT_FACTIONWAR_FOUR_1           = resultCode.RESULT_SYSTEM + 201 //双方公会经过激烈的战斗，%s最终技高一筹荣获得了本届公会战的冠军，%s获得亚军，祝贺他们！
//resultCode.RESULT_FACTIONWAR_FOUR_3           = resultCode.RESULT_SYSTEM + 202 //双方公会经过激烈的战斗，%s最终技高一筹荣获得了本届公会战的季军，祝贺他们！
//resultCode.RESULT_FACTIONWAR_START3           = resultCode.RESULT_SYSTEM + 203 //公会战冠军赛半决赛已经火热开启，请获得资格的军团成员迅速进入活动，为军团抢夺令牌展现军团实力！
//resultCode.RESULT_FACTIONWAR_START4           = resultCode.RESULT_SYSTEM + 204 //公会战冠军赛决赛已经火热开启，请获得资格的军团成员迅速进入活动，为军团抢夺令牌展现军团实力！

//公会任务
//resultCode.RESULT_FACTIONTASK_ENTER           = resultCode.RESULT_SYSTEM + 205 //您所在公会未获得第一名，无法进入藏宝阁！
//resultCode.RESULT_FACTIONTASK_ENTER2          = resultCode.RESULT_SYSTEM + 206 //加入公会不足七天，无法进入臧宝阁！
//resultCode.RESULT_ACTIONTASK_RANK             = resultCode.RESULT_SYSTEM + 207 //本次公会争霸，第一名公会：【%s】，第二名公会：【%s】，第三名公会：【%s】，恭喜这三个公会！
//resultCode.RESULT_FIRST_FACTION               = resultCode.RESULT_SYSTEM + 208 //欢迎【%s】会长【%s】
//
//resultCode.RESULT_ITEM_GET                    = resultCode.RESULT_ITEM_TIPS + 1 //获得%d[数量]个%d[物品]%d[品质]
//resultCode.RESULT_ITEM_DROP                   = resultCode.RESULT_ITEM_TIPS + 2 //失去%d[数量]个%d[物品]%d[品质]
//resultCode.RESULT_DISCOUNT_NO_ACT             = resultCode.RESULT_ITEM_TIPS + 3 //没有打折活动
//resultCode.RESULT_DISCOUNT_NOT_IN_TIME        = resultCode.RESULT_ITEM_TIPS + 4 //不在打折活动的时间里
//resultCode.RESULT_DISCOUNT_ACT_EXCHANGE       = resultCode.RESULT_ITEM_TIPS + 5 //活动的act_key变了 可能是开了新的活动
//resultCode.RESULT_DISCOUNT_NOT_SALE           = resultCode.RESULT_ITEM_TIPS + 6 //活动没有配置卖的物品
//resultCode.RESULT_DISCOUNT_WRONG_ID           = resultCode.RESULT_ITEM_TIPS + 7 //玩家指定的礼包ＩＤ不存在
//resultCode.RESULT_DISCOUNT_NOT_ENOUGH         = resultCode.RESULT_ITEM_TIPS + 8 //不够钱了
//resultCode.RESULT_STAR_EFFECT_ACTIVATED       = resultCode.RESULT_ITEM_TIPS + 9 //%s女仆获得%s品质装备共鸣属性
//resultCode.RESULT_EQUIP_STONE_OFF             = resultCode.RESULT_ITEM_TIPS + 10 //请先卸下融合装备的所有宝石
//resultCode.RESULT_EQUIP_SKILL_ACTIVATED       = resultCode.RESULT_ITEM_TIPS + 11 //%s女仆获得%s品质装备特技共鸣
//resultCode.RESULT_ROBBER_FACTION_ITEM         = resultCode.RESULT_ITEM_TIPS + 12 //获得小型军团物资并存入所在军团仓库！


//resultCode.RESULT_PET_GET_INTIMATE            = resultCode.RESULT_PET_TIPS + 86 //%s部下获得%d点亲密度
//resultCode.RESULT_PET_REDUCE_INTIMATE         = resultCode.RESULT_PET_TIPS + 87 //%s部下减少%d点亲密度


resultCode.RESULT_MINE_ONCE_PRIZE           = resultCode.RESULT_ACTIVITY_TIPS + 1 //开采%s%s#rf获得：积分*%s，%s%s#rf*%s
//resultCode.RESULT_WORLDBOSS_DAMAGE            = resultCode.RESULT_ACTIVITY_TIPS + 2 //%s对终极魔龙造成伤害为d%，暂时排在第一名
//resultCode.RESULT_WORLDBOSS_BOX               = resultCode.RESULT_ACTIVITY_TIPS + 3 //%s在终极魔龙的眼皮底下开启了冥界宝箱，获得大量宝藏
//resultCode.RESULT_WORLDBOSS_ENTER             = resultCode.RESULT_ACTIVITY_TIPS + 4 //%s前来挑战终极魔龙
//resultCode.RESULT_WORLDBOSS_LEAVE             = resultCode.RESULT_ACTIVITY_TIPS + 5 //%s撤出终极魔龙的地盘
//resultCode.RESULT_ROBBER_KICK                 = resultCode.RESULT_ACTIVITY_TIPS + 6 //%s被%s杀得人仰马翻，被赶出了混沌世界
//resultCode.RESULT_ROBBER_GANKTICKET           = resultCode.RESULT_ACTIVITY_TIPS + 7 //%s夺取了%s秘钥，大家快去抢夺吧，位置详细可以查看圣地小地图!!
//resultCode.RESULT_ROBBER_KILLBOSS             = resultCode.RESULT_ACTIVITY_TIPS + 8 //%s在%d区成功击杀了堕落魔人，获得大量宝藏！
//resultCode.RESULT_ROBBER_LOSTTICKET           = resultCode.RESULT_ACTIVITY_TIPS + 9 //%s在%d区被堕落魔人击败，丢失了挑战令牌
//resultCode.RESULT_ROBBER_ENTER_ROOM           = resultCode.RESULT_ACTIVITY_TIPS + 10 //%s进入了%d区
//resultCode.RESULT_ROBBER_LEAVE_ROOM           = resultCode.RESULT_ACTIVITY_TIPS + 11 //%s撤出了%d区
//resultCode.RESULT_RELIC_MINE_LEAVE            = resultCode.RESULT_ACTIVITY_TIPS + 12 //战斗过程中，对方刚好撤离了遗迹
//resultCode.RESULT_DEAD_FIELD_GATES            = resultCode.RESULT_ACTIVITY_TIPS + 13 //恭喜你成功通过第%d区
//resultCode.RESULT_SECRET_LAND_TIME_OUT        = resultCode.RESULT_ACTIVITY_TIPS + 14 //当前题目倒计时结束，题目刷新
//resultCode.RESULT_SECRET_LAND_SUCCESS         = resultCode.RESULT_ACTIVITY_TIPS + 15 //在玩家%s的带领下，正确解开了密语，获得丰厚奖励，希望少爷们的再接再厉
//resultCode.RESULT_SECRET_LAND_FAILD           = resultCode.RESULT_ACTIVITY_TIPS + 16 //本条答题解谜失败，全体人员受到百分之%d的伤害。
//resultCode.RESULT_CHRISTMAS_DAY_REFRESH       = resultCode.RESULT_ACTIVITY_TIPS + 17 //巴恩斯城、金字塔和精灵之都正下着纷纷小雪，雪花飘洋，快去收集雪花跟圣诞使者兑换礼物吧！
//resultCode.RESULT_NEWYEAR_DAY_REFRESH         = resultCode.RESULT_ACTIVITY_TIPS + 18 //巴恩斯城、金字塔和精灵之都出现了一批烟花小偷，他们把制造烟花的材料偷走了，打败他们夺回材料跟元旦使者兑换奖励吧！
//resultCode.RESULT_DEAD_FIELD_PERSONAL         = resultCode.RESULT_ACTIVITY_TIPS + 19 //%s玩家勇闯终极境地，成为全服首个通过%d层的勇者。
//resultCode.RESULT_ROBBER_NPC_BUSY             = resultCode.RESULT_ACTIVITY_TIPS + 20 //怪物被其它玩家挑战中！请稍后。
//resultCode.RESULT_SPRING_ONLINE               = resultCode.RESULT_ACTIVITY_TIPS + 21 //【玩家名字XXX】在新年运气爆棚通过在线奖励获得【xxx道具名字*数量】
//resultCode.RESULT_SPRING_MONSTER              = resultCode.RESULT_ACTIVITY_TIPS + 22 //英勇的【玩家名字XXX】打跑了正在做坏事的年兽，获得了【xxx道具名字*数量】
//resultCode.RESULT_SPRING_PLANT_MONEY_TREE     = resultCode.RESULT_ACTIVITY_TIPS + 23 //【%s】在【%s】种下了一颗摇钱树，大家快去摇一摇吧
//resultCode.FACWARSERVER_RANK1                 = resultCode.RESULT_ACTIVITY_TIPS + 24 //恭喜#yellow%s#rf获得了本次跨服军团战的冠军！在和#yellow%s#rf的激烈战斗中，#yellow%s#rf最终技高一筹击败了对方获得了最终的冠军！
//resultCode.FACWARSERVER_RANK2                 = resultCode.RESULT_ACTIVITY_TIPS + 25 //恭喜#yellow%s#rf,以强大实力获得了进入总决赛的资格！敬请各位关注！
//resultCode.FACWARSERVER_RANK4                 = resultCode.RESULT_ACTIVITY_TIPS + 26 //恭喜#yellow%s#rf,成为4强进入冠军赛，冠军赛将在明天开始，请留意相关信息！
//resultCode.FACWARSERVER_RANK16                = resultCode.RESULT_ACTIVITY_TIPS + 27 //经过激烈的比拼，#yellow%s#rf成功晋级16强！请期待接下来更加精彩的比赛！
//resultCode.FACWARSERVER_RANK8                 = resultCode.RESULT_ACTIVITY_TIPS + 28 //经过激烈的比拼，#yellow%s#rf成功晋级8强！请期待接下来更加精彩的比赛！
//resultCode.LEAGUE_COMMING                     = resultCode.RESULT_ACTIVITY_TIPS + 29 //跨服天梯将在22点开始，敬请期待
//resultCode.LEAGUE_CLOSING                     = resultCode.RESULT_ACTIVITY_TIPS + 30 //跨服天梯将在23:00关闭，请还在对战的玩家及时退出
//resultCode.LEAGUE_HAVE_CLOSE                  = resultCode.RESULT_ACTIVITY_TIPS + 31 //跨服天梯已经关闭，每晚22点开放一小时
//resultCode.PLR_RENAME                         = resultCode.RESULT_ACTIVITY_TIPS + 32 //%s使用%s改名为%s        (服务器发送的是物品entryId)
//resultCode.FACTION_MTX_OPEN                   = resultCode.RESULT_ACTIVITY_TIPS + 33 //灵阵守卫活动已经由%s军团的团长%s开启了，请大家参加
//resultCode.FACTION_MTX_ENTER_ONE              = resultCode.RESULT_ACTIVITY_TIPS + 34 //每周只能进入一次阵眼
//resultCode.FACTION_MTX_BROKEN                 = resultCode.RESULT_ACTIVITY_TIPS + 35 //阵眼已经被破坏
//resultCode.FACTION_MTX_GUARD_COMING           = resultCode.RESULT_ACTIVITY_TIPS + 36 //听说阵眼守护者已经出现，请速去挑战
//resultCode.FACTION_MTX_BROKEN                 = resultCode.RESULT_ACTIVITY_TIPS + 37 //经过大家的齐心协力，最后%s以迅雷不及掩耳之势给予守护者致命一击，成功击杀守护者！
//resultCode.FACTION_MTX_LEAVE                  = resultCode.RESULT_ACTIVITY_TIPS + 38 //副本内全体成员获得通关奖励，将在10秒后被送出副本。
//resultCode.FACTION_MTX_NO_UNION               = resultCode.RESULT_ACTIVITY_TIPS + 39 //没有加入联萌
//resultCode.FACTION_MTX_NO_FACTION             = resultCode.RESULT_ACTIVITY_TIPS + 40 //没有加入军团
//resultCode.FACTION_MTX_NOT_OPEN               = resultCode.RESULT_ACTIVITY_TIPS + 41 //灵阵没有开启
//resultCode.FACTION_BOSS_NOT_OPEN              = resultCode.RESULT_ACTIVITY_TIPS + 42 //BOSS没有开启，请先破坏阵眼
//resultCode.FACTION_BOSS_COOLDOWN              = resultCode.RESULT_ACTIVITY_TIPS + 43 //你还不能打BOSS,在冷却中
//resultCode.FACTION_TEACHER_NOT_OPEN           = resultCode.RESULT_ACTIVITY_TIPS + 44 //强化师还没有出来，请等待刷新
//resultCode.FACTION_TEACHER_COOLDOWN           = resultCode.RESULT_ACTIVITY_TIPS + 45 //你还不能打BOSS,在冷却中
//resultCode.FACTION_TEACHER_COMMING            = resultCode.RESULT_ACTIVITY_TIPS + 46 //强化师已经出现，灵阵的力量加强了，请速去对抗
//resultCode.FACTION_TEACHER_GONE               = resultCode.RESULT_ACTIVITY_TIPS + 47 //强化师已经被消灭，灵阵的力量回复正常
//resultCode.FACTION_BOSS_COMMING               = resultCode.RESULT_ACTIVITY_TIPS + 48 //boss出现了，请速去对抗
//resultCode.FACTION_BOSS_GONE                  = resultCode.RESULT_ACTIVITY_TIPS + 49 //boss已经被消灭，活动即将结束
//resultCode.FACTION_MTX_MPA_BROKEN_ONE         = resultCode.RESULT_ACTIVITY_TIPS + 50 //%s已经被破坏，请各位继续努力破坏剩下的阵眼
//resultCode.FACTION_MTX_MPA_ALL_BROKEN         = resultCode.RESULT_ACTIVITY_TIPS + 51 //%s已经被破坏，BOSS即将出现
//resultCode.FACTION_BEING_LIFE_COOLDOWN        = resultCode.RESULT_ACTIVITY_TIPS + 52 //刚复活，身体弱，请稍候再试
//resultCode.FACTION_MTX_JOIN_TIME_LIMIT        = resultCode.RESULT_ACTIVITY_TIPS + 53 //加入军团时间不足七天，不能参加这个活动
//resultCode.FACTION_MTX_MCH_PROMOTE            = resultCode.RESULT_ACTIVITY_TIPS + 54 //%s提升了福利机器！
//resultCode.FACTION_MTX_MCH_UPGRADE            = resultCode.RESULT_ACTIVITY_TIPS + 55 //福利机器升级成功，%d%%机会获得双倍奖励！
//resultCode.FACTION_MTX_DOUBLE_PRIZE           = resultCode.RESULT_ACTIVITY_TIPS + 56 //恭喜你，获得双倍奖励！
//resultCode.ONLINE_QUESTION_MAX_COUNT          = resultCode.RESULT_ACTIVITY_TIPS + 57 //今日已抢答成功%d次，无法再抢答
//resultCode.WORLD_BOSS_BOX_MAX_COUNT           = resultCode.RESULT_ACTIVITY_TIPS + 58 //今日已捡取宝箱%d次，无法再捡取
//resultCode.RESULT_MEAT_CREATE                 = resultCode.RESULT_ACTIVITY_TIPS + 59 //烤肉在%s刷新，请各位玩家前去拾取。
//
//resultCode.RESULT_FACTION_MAP_BOSS_ESCAPE     = resultCode.RESULT_ACTIVITY_TIPS + 60 //军团副本哥布林小怪逃跑了
//resultCode.RESULT_FACTION_MAP_OPENED          = resultCode.RESULT_ACTIVITY_TIPS + 61 //同一时间只能开启一个副本


//caidan
//resultCode.RESULT_EGPICK_LEVEL_LIMIT					=  resultCode.RESULT_ACTIVITY_TIPS + 62 //等级不足20，无法拾取

//faction
//resultCode.RESULT_FACTIONWAR_SENIOR_RECORD1							=  resultCode.RESULT_ACTIVITY_TIPS + 63
//resultCode.RESULT_FACTIONWAR_SENIOR_RECORD2							=  resultCode.RESULT_ACTIVITY_TIPS + 64 
//resultCode.RESULT_FACTIONWAR_SENIOR_RECORD3							=  resultCode.RESULT_ACTIVITY_TIPS + 65 
//resultCode.RESULT_FACTIONWAR_SENIOR_RECORD4							=  resultCode.RESULT_ACTIVITY_TIPS + 66 
//resultCode.RESULT_FACTIONWAR_SENIOR_RECORD5							=  resultCode.RESULT_ACTIVITY_TIPS + 67 
//resultCode.RESULT_FACTIONWAR_SENIOR_RECORD6							=  resultCode.RESULT_ACTIVITY_TIPS + 68 
//resultCode.RESULT_FACTIONWAR_SENIORPER									=  resultCode.RESULT_ACTIVITY_TIPS + 69		//精英赛准备公会频道公告
//resultCode.RESULT_FACTIONWAR_SENIORPER2									=  resultCode.RESULT_ACTIVITY_TIPS + 70		//精英赛准备公会频道公告
//resultCode.RESULT_FACTIONWAR_RANK16											=  resultCode.RESULT_ACTIVITY_TIPS + 71		//通过筛选进入淘汰赛 公会频道公告
//resultCode.RESULT_FACTIONWAR_RANK4											=  resultCode.RESULT_ACTIVITY_TIPS + 72		//进入冠军赛 公会频道公告


//resultCode.RESULT_TASK_INTIMATE_ACCEP         = resultCode.RESULT_TASK_TIPS + 75 // 部下%s亲密度达到%d，触发部下任务
resultCode.RESULT_TASK_ADD_TASK               = resultCode.RESULT_TASK_TIPS + 76 // 接受任务：%s
resultCode.RESULT_TASK_FINISH                 = resultCode.RESULT_TASK_TIPS + 77 // 完成任务：%d
resultCode.RESULT_TASK_ACCEPT                 = resultCode.RESULT_TASK_TIPS + 78 // 任务接受：%d
//resultCode.RESULT_TASK_PET_LEVEL              = resultCode.RESULT_TASK_TIPS + 79 // 等级不足%d级
//resultCode.RESULT_TASK_PET_ACTIVE             = resultCode.RESULT_TASK_TIPS + 80 // 觉醒等级不足%d级
//resultCode.RESULT_TASK_PET_BREAK              = resultCode.RESULT_TASK_TIPS + 81 // 突破等级不足%d级
//resultCode.RESULT_TASK_PET_SKILL              = resultCode.RESULT_TASK_TIPS + 82 // 需要强化的技能没有解锁
//resultCode.RESULT_TASK_SKILL_COUNT            = resultCode.RESULT_TASK_TIPS + 83 // 该类型的任务数量已经达到上限

//resultCode.RESULT_ROLE_WU_DOU_POINT           = resultCode.RESULT_ROLE_TIPS + 1      // 获得斗技积分:%d
//resultCode.RESULT_ROLE_ADD_EXP                = resultCode.RESULT_ROLE_TIPS + 2      // 主角获得%d点经验
resultCode.RESULT_BLACK_ROLE_EXIST            = resultCode.RESULT_ROLE_TIPS + 3      // 角色已经在黑名单里了
resultCode.RESULT_BLACK_ROLE_TOO_MUCH         = resultCode.RESULT_ROLE_TIPS + 4      // 黑名单里数理已经到了最大
resultCode.RESULT_BLACK_ROLE_NOT_EXIST        = resultCode.RESULT_ROLE_TIPS + 5      // 黑名单里没有这个角色
resultCode.RESULT_BLACK_ROLE_ADD_OK           = resultCode.RESULT_ROLE_TIPS + 6      // 加入黑名单成功
resultCode.RESULT_BLACK_ROLE_REMOVE_OK        = resultCode.RESULT_ROLE_TIPS + 7      // 删除黑名单成功
//resultCode.RESULT_ROLE_VIP13_LOGIN            = resultCode.RESULT_ROLE_TIPS + 8      // vip13的玩家登陆游戏
//resultCode.RESULT_ROLE_VIP14_LOGIN            = resultCode.RESULT_ROLE_TIPS + 9      // vip14的玩家登陆游戏
//resultCode.RESULT_ROLE_VIP15_LOGIN            = resultCode.RESULT_ROLE_TIPS + 10     // vip15的玩家登陆游戏
//resultCode.RESULT_ROLE_VIP16_LOGIN            = resultCode.RESULT_ROLE_TIPS + 11     // vip16的玩家登陆游戏
//resultCode.RESULT_GUOZHAN_BUILD               = resultCode.RESULT_ROLE_TIPS + 12     //同时最多只能有一个建筑进行建造
//resultCode.RESULT_GUOZHAN_BUILD_MAX           = resultCode.RESULT_ROLE_TIPS + 13     //该建筑物不可再建造
//resultCode.RESULT_GUOZHAN_GOLD_DEC            = resultCode.RESULT_ROLE_TIPS + 14     //国战晶石减少
//resultCode.RESULT_GUOZHAN_GOLD_ADD            = resultCode.RESULT_ROLE_TIPS + 15     //国战晶石增加
//resultCode.RESULT_WING_REFINING_ADD           = resultCode.RESULT_ROLE_TIPS + 16     //翅膀炼化值增加%d
//resultCode.RESULT_WING_REFINING_REDUCE        = resultCode.RESULT_ROLE_TIPS + 17     //翅膀炼化值减少%d
//resultCode.RESULT_WING_REFINING_LVUP          = resultCode.RESULT_ROLE_TIPS + 18     //翅膀炼化升级
//resultCode.RESULT_GUOZHAN_MAKE_WEAPON         = resultCode.RESULT_ROLE_TIPS + 19     //同时只能制作一个
//resultCode.RESULT_FACITON_BUILD_GET_POINT     = resultCode.RESULT_ROLE_TIPS + 20     //获得军团建筑积分
//resultCode.RESULT_FACITON_BUILD_USE_POINT     = resultCode.RESULT_ROLE_TIPS + 21     //消耗军团建筑积分
//resultCode.RESULT_FACITON_BUILD_SCHEDULE_FULL = resultCode.RESULT_ROLE_TIPS + 22     //建设进度已满！
//resultCode.RESULT_FACITON_BUILD_MAX_LEVEL     = resultCode.RESULT_ROLE_TIPS + 23     //建筑已满级！
//resultCode.RESULT_CREATE_TIME_LIMIT           = resultCode.RESULT_ROLE_TIPS + 24     //%d分钟内不能再次创建
//resultCode.ROLE_LEVEL_LIMIT                   = resultCode.RESULT_ROLE_TIPS + 25     //等级不足%d级
//resultCode.ROLE_GROUP_MAX_COUNT_LIMIT         = resultCode.RESULT_ROLE_TIPS + 26     //个人聊天组已经达到上限
//resultCode.ROLE_GROUP_CREATE_COUNT_LIMIT      = resultCode.RESULT_ROLE_TIPS + 27     //个人创建数量已经达到上限
//resultCode.ROLE_GROUP_RELEASE                 = resultCode.RESULT_ROLE_TIPS + 28     //该讨论组已经解散
//resultCode.RESULT_FACITON_SKILL_FACLEVEL      = resultCode.RESULT_ROLE_TIPS + 29     //军团等级不足
//resultCode.RESULT_FACITON_SKILL_FACPOINT      = resultCode.RESULT_ROLE_TIPS + 30     //军团历史贡献度不足
//resultCode.RESULT_FACITON_SKILL_LEVEL_LIMIT   = resultCode.RESULT_ROLE_TIPS + 31     //军团技能上限
//resultCode.RESULT_FACITON_TASK_NO_TASK        = resultCode.RESULT_ROLE_TIPS + 32     //当天军团任务全部被领完
//resultCode.RESULT_FACITON_TASK_DAILY_COUNT    = resultCode.RESULT_ROLE_TIPS + 33     //军团任务次数上限
//resultCode.RESULT_FACITON_TASK_CANCEL_GOLD    = resultCode.RESULT_ROLE_TIPS + 34     //取消军团任务晶石不足
//resultCode.RESULT_FACITON_TASK_TIME_LIMIT     = resultCode.RESULT_ROLE_TIPS + 35     //军团任务时间限制
//resultCode.RESULT_SHAPESHIFTING               = resultCode.RESULT_ROLE_TIPS + 36     //变身之中不能攻击
//resultCode.RESULT_TEAM_PVE_POINT_ADD          = resultCode.RESULT_ROLE_TIPS + 37     //增加骑士团副本积分%d
//resultCode.RESULT_TEAM_PVE_POINT_DEC          = resultCode.RESULT_ROLE_TIPS + 38     //减少骑士团副本积分%d
//resultCode.RESULT_RIDE_EQUIP_COUNT_LIMIT      = resultCode.RESULT_ROLE_TIPS + 39     //携带的坐骑装备已达到数量上限

//yixiu
//resultCode.RESULT_ACTOR_SUCCESS               = resultCode.RESULT_ROLE_TIPS + 40 //恭喜成功了
//resultCode.RESULT_ACTOR_NOT_SUCCESS           = resultCode.RESULT_ROLE_TIPS + 41 //很遗憾，失败了
//resultCode.RESULT_ACTOR_NOT_ENTRYINFO         = resultCode.RESULT_ROLE_TIPS + 42 //没有相关操作信息
//resultCode.RESULT_ACTOR_NOT_FUNDS             = resultCode.RESULT_ROLE_TIPS + 43 //金币不足
//resultCode.RESULT_ACTOR_NOT_GOLD              = resultCode.RESULT_ROLE_TIPS + 44 //晶石不足
//resultCode.RESULT_ACTOR_NOT_ITEM_LIST         = resultCode.RESULT_ROLE_TIPS + 45 //物品不足
//resultCode.RESULT_ACTOR_NOT_PLR_LEVEL         = resultCode.RESULT_ROLE_TIPS + 46 //角色等级限制
//resultCode.RESULT_ACTOR_NOT_PET_LEVEL         = resultCode.RESULT_ROLE_TIPS + 47 //伙伴等级限制
//resultCode.RESULT_ACTOR_VOCATION_UNLOCK       = resultCode.RESULT_ROLE_TIPS + 48 //职业未解锁
//resultCode.RESULT_ACTOR_NOT_FINISH_TASK       = resultCode.RESULT_ROLE_TIPS + 49 //相关任务没有完成
//resultCode.RESULT_ACTOR_NOT_ABILITY           = resultCode.RESULT_ROLE_TIPS + 50 //养成属性限制
//resultCode.RESULT_ACTOR_NOT_OBJECT            = resultCode.RESULT_ROLE_TIPS + 51 //没有相关操作对象
//resultCode.RESULT_ACTOR_NOT_BREAK_LEVEL       = resultCode.RESULT_ROLE_TIPS + 52 //突破等级限制
//resultCode.RESULT_ACTOR_NOT_AWAKE_LEVEL       = resultCode.RESULT_ROLE_TIPS + 53 //觉醒等级限制
//resultCode.RESULT_ACTOR_MAX_LEVEL             = resultCode.RESULT_ROLE_TIPS + 54 //最大等级限制
//resultCode.RESULT_ACTOR_PACKET_FULL           = resultCode.RESULT_ROLE_TIPS + 55 //背包已满
//resultCode.RESULT_ACTOR_LINK_LEVEL            = resultCode.RESULT_ROLE_TIPS + 56 //羁绊等级限制
//resultCode.RESULT_ACTOR_SYSTEM_ERROR          = resultCode.RESULT_ROLE_TIPS + 57 //系统相关数据错误
//resultCode.RESULT_MESSAGE_MAX_LENGTH          = resultCode.RESULT_ROLE_TIPS + 58 //留言超过最大长度
//resultCode.RESULT_MESSAGE_MAX_COUNT           = resultCode.RESULT_ROLE_TIPS + 59 //对方留言板空间已满
//resultCode.RESULT_PRAISE_ALREADY              = resultCode.RESULT_ROLE_TIPS + 60 //你今天已经点过赞了
//resultCode.RESULT_SEND_FLOWER                 = resultCode.RESULT_ROLE_TIPS + 61 //%s%s
//resultCode.RESULT_SET_HOME_PAGE_GIFT          = resultCode.RESULT_ROLE_TIPS + 62 //%s在个人主页中设置了奖励，大家快去点个赞吧_LINK_
//resultCode.RESULT_SUCCESS_APPLY               = resultCode.RESULT_ROLE_TIPS + 63 //申请成功
resultCode.RESULT_SUCCESS_INVITE              = resultCode.RESULT_ROLE_TIPS + 64 //邀请成功
//resultCode.RESULT_EMPLOY_DAILY_MAX_COUNT      = resultCode.RESULT_ROLE_TIPS + 65 //达到每日最大雇佣次数
//resultCode.RESULT_EMPLOY_COMMON               = resultCode.RESULT_ROLE_TIPS + 66 //不能雇佣同一个人的队伍
//resultCode.RESULT_BE_EMPLOYED_MAX_COUNT       = resultCode.RESULT_ROLE_TIPS + 67 //被雇佣次数达到上限
//resultCode.RESULT_EMPLOY_OVER_TIME            = resultCode.RESULT_ROLE_TIPS + 68 //雇佣队伍已过期，等待下架中
//resultCode.RESULT_NOT_MY_FACTION              = resultCode.RESULT_ROLE_TIPS + 69 //不是本军团的，不能操作
//resultCode.RESULT_EMPLOY_MAX_COUNT            = resultCode.RESULT_ROLE_TIPS + 70 //达到个人雇佣组携带上限
resultCode.RESULT_PLAYER_RECEVIE_MAX_COUNT    = resultCode.RESULT_ROLE_TIPS + 72 //对方达到每日接收上限
resultCode.RESULT_PLAYER_NOT_FRIEND           = resultCode.RESULT_ROLE_TIPS + 73 //对方与你不是好友
resultCode.RESULT_PLAYER_SEND_MAX_COUNT       = resultCode.RESULT_ROLE_TIPS + 74 //达到每日赠送上限
resultCode.RESULT_SAME_PLAYER_SEND            = resultCode.RESULT_ROLE_TIPS + 75 //不能赠送相同好友
resultCode.RESULT_GET_MONEY_UNIT              = resultCode.RESULT_ROLE_TIPS + 76 //获得%d%d PS:获得xx晶石 获得xx竞技积分
resultCode.RESULT_USE_MONEY_UNIT              = resultCode.RESULT_ROLE_TIPS + 77 //失去%d%d PS:获得xx晶石 获得xx竞技积分
resultCode.RESULT_EXCITE_LIMIT                = resultCode.RESULT_ROLE_TIPS + 78 //恭喜限时通关%d,获得%d钻石
//resultCode.RESULT_ROBBER_NO_POWER             = resultCode.RESULT_ROLE_TIPS + 79 //不消耗体力只能获得较少奖励
//resultCode.RESULT_ROBBER_HANG_UP_FAIL         = resultCode.RESULT_ROLE_TIPS + 80 //设置挂机失败
//resultCode.RESULT_ROBBER_HARD_COUNT_LIMIT     = resultCode.RESULT_ROLE_TIPS + 81 //%s击杀数量%d,已达到上限
//resultCode.RESULT_ROBBER_HARD_KILLED          = resultCode.RESULT_ROLE_TIPS + 82 //%s在圣地击杀一个精英怪,还剩余%d个精英怪，大家快去杀吧！！
//resultCode.RESULT_PLAYER_IN_COMBAT            = resultCode.RESULT_ROLE_TIPS + 83 //对方或者己方正在处于战斗中
//resultCode.RESULT_PLAYER_FIGHT_TEAM_MEMBER    = resultCode.RESULT_ROLE_TIPS + 84 //不能挑战自己队友
//resultCode.RESULT_ROBBER_HANG_LIST_MAX_COUNT  = resultCode.RESULT_ROLE_TIPS + 85 //圣地挂机人数达到了最高上限，挂机失败
//resultCode.RESULT_ROBBER_MAX_PLAYER           = resultCode.RESULT_ROLE_TIPS + 86 //圣地在线人数达到最高上限，请稍后再进
resultCode.RESULT_TEAM_ACTIVITY_LINK          = resultCode.RESULT_ROLE_TIPS + 87 //%s进组啦~//9;%s;1;加入队伍//!
//resultCode.RESULT_SACRIFICE_FAILED            = resultCode.RESULT_ROLE_TIPS + 88 //御灵升级失败
//resultCode.RESULT_SACRIFICE_SUCCESS           = resultCode.RESULT_ROLE_TIPS + 89 //御灵升级成功
//resultCode.RESULT_GET_DAILY_POWER_SUCCESS     = resultCode.RESULT_ROLE_TIPS + 90 //领取行动力成功
//resultCode.RESULT_EQUIP_IDENTIFY_SUCCESS      = resultCode.RESULT_ROLE_TIPS + 91 //恭喜你，鉴定成功,生成了特效！！
//resultCode.RESULT_DROP_PARTNER_VOCATION       = resultCode.RESULT_ROLE_TIPS + 92 //您失去了一个名叫#yellow%s#rf的伙伴
//resultCode.ROBBER_MEMBER_HAVE_TICKET          = resultCode.RESULT_ROLE_TIPS + 93 //持有秘钥不能与npc战斗
//resultCode.RESULT_EQUIP_RESONATE              = resultCode.RESULT_ROLE_TIPS + 94 //产生了%d%s共鸣 PS:产生了5阶等级共鸣
//resultCode.RESULT_VOCATION_NOT_DEAD           = resultCode.RESULT_ROLE_TIPS + 95 //主角还没有死亡
//resultCode.RESULT_VOCATION_REVIVE_SUCCESS     = resultCode.RESULT_ROLE_TIPS + 96 //主角复活成功
//resultCode.RESULT_PLAYER_GET_EXP              = resultCode.RESULT_ROLE_TIPS + 97 //获得%d点经验
//resultCode.RESULT_PET_LEVEL_OVER_PLR_LEVEL    = resultCode.RESULT_ROLE_TIPS + 98 //伙伴等级不能高于主角等级
//resultCode.RESULT_PET_GET_EXP                 = resultCode.RESULT_ROLE_TIPS + 99 //%d伙伴获得%d点经验
//resultCode.RESULT_ROBBER_ITEM_GET             = resultCode.RESULT_ROLE_TIPS + 100 //圣地挂机:获得%d[数量]个%d[物品]%d[品质]
//resultCode.RESULT_ROBBER_GET_MONEY_UNIT       = resultCode.RESULT_ROLE_TIPS + 101 //圣地挂机:获得%d%d PS:获得xx晶石 获得xx竞技积分
//resultCode.RESULT_ROBBER_PLAYER_GET_EXP       = resultCode.RESULT_ROLE_TIPS + 102 //圣地挂机:角色获得%d点经验
//resultCode.RESULT_ROBBER_PET_LEVEL_OVER       = resultCode.RESULT_ROLE_TIPS + 103 //圣地挂机:伙伴等级不能高于主角等级
//resultCode.RESULT_ROBBER_PET_GET_EXP          = resultCode.RESULT_ROLE_TIPS + 104 //圣地挂机:%d伙伴获得%d点经验
//resultCode.RESULT_ROBBER_KILL_STATUS_POWER    = resultCode.RESULT_ROLE_TIPS + 105 //恶徒或者修罗状态不能领取行动力
//resultCode.RESULT_LOST_TEMPLE_BEGIN           = resultCode.RESULT_ROLE_TIPS + 106 //众神祗在圣地中丢弃大量魔盒，快去拾取吧，可以获得魔盒中宝藏哦
//resultCode.RESULT_LOST_TEMPLE_END             = resultCode.RESULT_ROLE_TIPS + 107 //众神祗已经离开圣地了，活动结束！
//resultCode.RESULT_ROBBER_TICKET_SCORE_STATUS  = resultCode.RESULT_ROLE_TIPS + 108 //%s携带有钥匙或者神像，不能攻击npc
//resultCode.RESULT_EQUIP_IDENTIFY_FAILD        = resultCode.RESULT_ROLE_TIPS + 109 //很遗憾，鉴定失败了,没有生成特效。
//resultCode.RESULT_HOME_PAGE_POUND_EGG         = resultCode.RESULT_ROLE_TIPS + 110 //你被%s砸了%s个鸡蛋，魅力减少了%s
resultCode.RESULT_NOT_FIGHT_FAST_END          = resultCode.RESULT_ROLE_TIPS + 111 //当前战斗不能快速退出
//resultCode.RESULT_ROBBER_NOT_TEAM_HANG        = resultCode.RESULT_ROLE_TIPS + 112 //组队状态下不可以挂机
//resultCode.RESULT_TASK_ACCEPT_MEMBER_COUNT    = resultCode.RESULT_ROLE_TIPS + 113 //组队在线人数不足
//resultCode.RESULT_TASK_CANCEL_MEMBER_OUT      = resultCode.RESULT_ROLE_TIPS + 114 //队友离队,组队任务取消,需要重新领取
//resultCode.RESULT_ROBBER_NOT_TEAM_GRADE       = resultCode.RESULT_ROLE_TIPS + 115 //组队状态下不可以进行评级战斗
//resultCode.RESULT_TASK_FINISH_COUNT_LIMIT     = resultCode.RESULT_ROLE_TIPS + 116 //任务完成次数达到上限,无法获取奖励
//resultCode.RESULT_TASK_TEAM_FOLLOWER          = resultCode.RESULT_ROLE_TIPS + 117 //你或者对方处于任务跟随状态
//resultCode.RESULT_ACTIVITY_DATA_REFRESH       = resultCode.RESULT_ROLE_TIPS + 118 //活动数据已刷新，请重新进入活动！
//resultCode.RESULT_TASK_CANCEL_CAPTAIN_CHANGE  = resultCode.RESULT_ROLE_TIPS + 119 //队长转换，组队任务取消，需要重新领取
//resultCode.RESULT_TASK_CANCEL_LEAVE_ROBBER    = resultCode.RESULT_ROLE_TIPS + 120 //战斗失败离开圣地，组队任务取消，需要重新领取
//resultCode.RESULT_ROBBER_PICK_BOSS_BOX        = resultCode.RESULT_ROLE_TIPS + 121 //boss不是你击杀的，还需要等待%s秒才能拾取
//resultCode.ROBBER_MEMBER_HAVE_BOSS_BOX        = resultCode.RESULT_ROLE_TIPS + 121 //持有boss宝箱不能与npc战斗
//resultCode.RESULT_ROBBER_BOSS_COUNT_LIMIT     = resultCode.RESULT_ROLE_TIPS + 122 //当前这种boss击杀数量已达到上限
//resultCode.RESULT_ROBBER_BOSS_BOX_MINE_LIMIT  = resultCode.RESULT_ROLE_TIPS + 123 //你抢夺宝箱次数已满，不能再抢夺对方的boss宝箱
//resultCode.RESULT_ROBBER_BOSS_BOX_OTHER_LIMIT = resultCode.RESULT_ROLE_TIPS + 123 //对方宝箱抢夺次数已满，不能在有宝箱的状态下和对方pk
//resultCode.RESULT_ROBBER_BOTH_BOSS_BOX_STATUS = resultCode.RESULT_ROLE_TIPS + 124 //你和对方都有boss宝箱状态,不能pk
//resultCode.RESULT_ROBBER_BOSS_BOX_PRIZE_COUNT = resultCode.RESULT_ROLE_TIPS + 125 //今天已经超过最大奖励次数了
//resultCode.RESULT_ROBBER_OFFLINE_HANG         = resultCode.RESULT_ROLE_TIPS + 126 //当前玩家正在离线挂机，不能被pk
//resultCode.RESULT_ROBBER_DROP_FASTEST         = resultCode.RESULT_ROLE_TIPS + 127 //恭喜【%s】在圣地中获得【%s】，用时%d秒钟创造该物品掉落记录。
//resultCode.RESULT_ROBBER_DROP_FAST_AVAGE      = resultCode.RESULT_ROLE_TIPS + 128 //恭喜你获得【%s】，时间为%秒，低于全服平均时间
//resultCode.RESULT_ROBBER_DROP_SLOW_AVAGE      = resultCode.RESULT_ROLE_TIPS + 129 //恭喜你获得【%s】，用时为%s秒，虽然超出平均时间，但是还是成功获得了物品哦
//resultCode.RESULT_ROBBER_NO_FACTION_OR_STATUS = resultCode.RESULT_ROLE_TIPS + 130 //没有工会，不能持有秘钥
//resultCode.RESULT_TEAM_NOT_ACTIVITY           = resultCode.RESULT_ROLE_TIPS + 131 //你或者队员不在活动内
//resultCode.RESULT_ROBBER_BOSS_STATUS_EXSIT    = resultCode.RESULT_ROLE_TIPS + 132 //已经拥有了boss宝箱了,不能重复持有
//resultCode.RESULT_ROBBER_TICKET_STATUS_EXSIT  = resultCode.RESULT_ROLE_TIPS + 133 //已经拥有了宝箱钥匙了,不能重复持有
//resultCode.RESULT_UNLOCK_VOCATION_TIPS        = resultCode.RESULT_ROLE_TIPS + 134 //恭喜XXXXX成功解锁%d!
//resultCode.RESULT_HOME_PAGE_POUND_EGGS        = resultCode.RESULT_ROLE_TIPS + 135 //XXXX向XXX砸了一砸82年的陈年烂鸡蛋，XXXX（被砸者）瞬间成了一具蛋挞！
//resultCode.RESULT_PARTNER_EVOLVE_MAX          = resultCode.RESULT_ROLE_TIPS + 136 //%s已经进化到最高阶
//resultCode.RESULT_PARTNER_EVOLVE_UP           = resultCode.RESULT_ROLE_TIPS + 137 //%s已经进化成功
//resultCode.RESULT_PARTNER_EVOLVE_UP           = resultCode.RESULT_ROLE_TIPS + 137 //%s已经进化成功
//resultCode.RESULT_TEAM_IN_BATTLE              = resultCode.RESULT_ROLE_TIPS + 138 //队伍正在战斗中,请稍候回归队伍
//resultCode.RESULT_HOME_PAGE_GIFT              = resultCode.RESULT_ROLE_TIPS + 139 //我已经在个人主页放置神秘礼物，点赞会有惊喜噢~
//resultCode.RESULT_HOME_PAGE_ICON              = resultCode.RESULT_ROLE_TIPS + 140 //我的个人主页更新啦，欢迎大家踩踩！
resultCode.RESULT_FIRST_FINISH_CHAMPION       = resultCode.RESULT_ROLE_TIPS + 141 //%s一路过关斩将，首个成为竞技场排名%s的勇者，恭喜贺喜。
resultCode.RESULT_GET_PRIZE_MAX_COUNT         = resultCode.RESULT_ROLE_TIPS + 142 //领取达到上限
//resultCode.RESULT_PUSHPRAISE_PRIZE            = resultCode.RESULT_ROLE_TIPS + 143 //恭喜%s通过点赞获得神秘礼物一份！
//resultCode.RESULT_PRAISE_MAX                  = resultCode.RESULT_ROLE_TIPS + 144 //今天点赞已达上限，请明天在来
//resultCode.RESULT_PUSHPRAISE_NOPRIZE          = resultCode.RESULT_ROLE_TIPS + 145	//点赞成功，但是没有获得礼物
resultCode.RESULT_ISCENTERSERVER              = resultCode.RESULT_ROLE_TIPS + 146	//跨服中无法操作
//resultCode.RESULT_SKY_HISTORY_LAYER           = resultCode.RESULT_ROLE_TIPS + 147	//需要达到地宫历史最高层%s层
//resultCode.RESULT_RIDDLE_BOX_FINISH           = resultCode.RESULT_ROLE_TIPS + 148	//惊喜宝箱刚出来就被拾取完了！呜呜呜~~~
//resultCode.RESULT_RELIC_MINE_PVP_WIN          = resultCode.RESULT_ROLE_TIPS + 149	//成功抢夺【%s】的商船
//resultCode.RESULT_EMPLOY_MAX_RENT_COUNT       = resultCode.RESULT_ROLE_TIPS + 150	//入驻数量达到系统上限，入驻失败
//resultCode.RESULT_ROBBER_PUNISH               = resultCode.RESULT_ROLE_TIPS + 151	//#yellow%s#rf战斗失败惩罚中（剩余%d秒）
//resultCode.RESULT_WILL_TEAM_EXIST             = resultCode.RESULT_ROLE_TIPS + 152	//你已经创建了一个，不能重复创建，但你可以修改组队意愿
resultCode.RESULT_VIEDO_OVER_TIME             = resultCode.RESULT_ROLE_TIPS + 153	//抱歉，录像已过期，无法查看了
//resultCode.RESULT_WILL_TEAM_EXIST             = resultCode.RESULT_ROLE_TIPS + 152	//你已经创建了一个，不能重复创建，但你可以修改组队意愿
//resultCode.REFUSE_EMPLOY_APPLY                = resultCode.RESULT_ROLE_TIPS + 153	//#yellow%s#rf会长拒绝了你的雇佣申请
//resultCode.EMPLOY_APPLY_PASS                  = resultCode.RESULT_ROLE_TIPS + 154	//#yellow%s#rf会长同意了你的雇佣申请
//resultCode.RESULT_EMPLOY_LEADER               = resultCode.RESULT_ROLE_TIPS + 155	//你已经创建了一个，不能重复创建，但你可以修改组队意愿
resultCode.RESULT_FACTION_NO_CHECK            = resultCode.RESULT_ROLE_TIPS + 156	//没有权限
//resultCode.RESULT_USE_CALL_STONE              = resultCode.RESULT_ROLE_TIPS + 157 //%s玩家使用%s，获得女神%s%s。
//resultCode.RESULT_LEAVE_ROBBER_CREATE_TICKET  = resultCode.RESULT_ROLE_TIPS + 158 //%s玩家离开圣地,钥匙重新刷新在了圣地，详细位置可以查看小地图!!
//resultCode.RESULT_KILL_ROBBER_CREATE_TICKET   = resultCode.RESULT_ROLE_TIPS + 159 //%s玩家被打的丢盔弃甲，狼狈而逃，抢夺者%s的详细位置可以查看小地图!!
//resultCode.RESULT_ROBBER_ENTER_SINGLE_SPACE   = resultCode.RESULT_ROLE_TIPS + 160 //%s持有钥匙或者boss宝箱或者魔盒或者处于战斗中，不能进行当前活动
//resultCode.RESULT_SKY_TOWER_CAMPAGIN          = resultCode.RESULT_ROLE_TIPS + 161 //%s需要先通关%s才能开启本层战斗
//resultCode.RESULT_QUIT_FACTION_TIME           = resultCode.RESULT_ROLE_TIPS + 162 //退出公会不足%s天，不能参加次活动

resultCode.RESULT_ALTER_FACTION_FORCE_SUCCESS = resultCode.RESULT_ROLE_TIPS + 163 //修改公会战力成功
resultCode.RESULT_REFUSE_MARRIAGE 			  = resultCode.RESULT_ROLE_TIPS + 164	//%s拒绝求婚
resultCode.RESULT_SHITU						  = resultCode.RESULT_ROLE_TIPS + 165	//%s正在寻觅一名良师，师徒双方可获得大量经验和突破丹，仙君赶紧来寻高徒吧
resultCode.RESULT_WULIN_WIN					  =	resultCode.RESULT_ROLE_TIPS + 166	//%s挑战了%s，胜利
resultCode.RESULT_WULIN_LOSE				  =	resultCode.RESULT_ROLE_TIPS + 167	//%s挑战了%s，失败
resultCode.RESULT_MINUTE_PRIZE 				  =	resultCode.RESULT_ROLE_TIPS + 168	//不同层获得每分钟奖励不同，本次获得%s
resultCode.RESULT_MENG_ZHU		 			  = resultCode.RESULT_ROLE_TIPS + 169	//%s成为武林盟主
resultCode.RESULT_STRONGHOLD_EVACUATE         = resultCode.RESULT_ROLE_TIPS + 171	//撤离成功
resultCode.RESULT_STRONGHOLD_HAS_EVACUATE     = resultCode.RESULT_ROLE_TIPS + 172	//该玩家已撤离
resultCode.RESULT_STRONGHOLD_HAS_OCCUPY	      = resultCode.RESULT_ROLE_TIPS + 173	//该据点已被占领
resultCode.RESULT_STRONGHOLD_OCCUPY_ONE       = resultCode.RESULT_ROLE_TIPS + 174	//只能占领一个据点
resultCode.RESULT_STRONGHOLD_OCCUPY_SUCCESS   = resultCode.RESULT_ROLE_TIPS + 175	//占领成功
resultCode.RESULT_STRONGHOLD_REVENGEING       = resultCode.RESULT_ROLE_TIPS + 176	//其他玩家正在帮忙复仇中
resultCode.RESULT_STRONGHOLD_HAS_REVENGEING   = resultCode.RESULT_ROLE_TIPS + 177	//已经复仇成功了
resultCode.RESULT_STRONGHOLD_ACTIVI_START     = resultCode.RESULT_ROLE_TIPS + 178	//据点boss活动已经开启，快去挑战吧！！！
resultCode.RESULT_STRONGHOLD_REVENGE_SELF     = resultCode.RESULT_ROLE_TIPS + 179	//你是掠夺者，无法帮助公会好友复仇。
resultCode.RESULT_STRONGHOLD_MAP_MAX_PLRCOUNT = resultCode.RESULT_ROLE_TIPS + 180	//天宫地图人数达到上限无法进入
